#!/bin/bash

. "${PWD}/.dev/utility.sh"

stop() {
    if [[ "$2" != "" ]]; then
        error "$2"

        println ""
    fi

    section "stop pre commit hook"
    exit $1
}

check_container_dev() {
    if [[ $(check_container "${CONTAINER_DEV}") != 0 ]]; then
        println ""

        stop 1 "$(error_container ${CONTAINER_DEV})"
    fi
}

go_fmt() {
    print_command "start go fmt"
    println ""

    UNFORMATTED=$(run_in_container_dev gofmt -l .)

    if [[ "${UNFORMATTED}" != "" ]]; then
        print_error "run 'gofmt -w' on the files listed above before commit"
        println "${UNFORMATTED}"
        stop 1
    fi

    print_command "end go fmt"
}

go_vet() {
    print_command "start go vet"
    println ""

    run_in_container_dev go vet ./...

    if [[ $? != 0 ]]; then
        print_error "fix the errors before commit"
        stop 1
    fi

    print_command "end go vet"
}

go_build() {
    print_command "start go build"
    println ""

    run_in_container_dev go build ./...

    if [[ $? != 0 ]]; then
        print_error "fix the errors before commit"
        stop 1
    fi

    print_command "end go build"
}

go_test() {
    print_command "start go test"
    println ""

    run_in_container_dev go test ./...

    if [[ $? != 0 ]]; then
        print_error "fix the errors before commit"
        stop 1
    fi

    print_command "end go test"
}

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

print_command "${PWD} start pre commit hook"

if [[ "${STAGED_FILES}" = "" ]]; then
    println "no files to commit"

    stop 0
fi

println ""

print_command "staged files start"
println "${STAGED_FILES}"
print_command "staged files end"

check_container_dev

STAGED_FILES_GO=$(git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\.go$)
if [[ "${STAGED_FILES_GO}" != "" ]]; then
    go_fmt

    println ""

    go_vet

    println ""

    go_build

    println ""

    go_test
fi

println ""

stop 0
